- name: practice
  hosts: all
  tasks:
    - name: print hello world
      ansible.builtin.debug:
        msg: hello world

    - name: demo variable
      hosts: all
      vars:
        url: examples.com
      tasks:
        - name: print a variable
          ansible.builtin.debug:
            msg: "{{url}}"