- name: practice
  hosts: localhost
  tasks:
    - name: print hello world
      ansible.builtin.debug:
        msg: hello world

- name: demo on vars
  hosts: localhost
  vars:
    url: examples.com
  tasks:
    - name: print a variable
      ansible.builtin.debug:
        msg: "{{ url }}"