- name: backend
  hosts: all
  become: yes
  tasks:
    - name: copy mysql
      ansible.builtin.copy:
        src: mys.conf
        dest: /etc/yum.repos.d/mysql.repo
    - name: remove old sql
      ansible.builtin.shell: dnf module disable mysql -y
    - name: install mysql server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present
    - name: restart mysql server
      ansible.builtin.systemd:
        name: mysql
        state: restarted
    - name: set root passwd
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
